[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/add-reservation"
  to = "http://prayers-reservation-server-production.up.railway.app/add-reservation"
  status = 200
  force = true
  conditions = { Country = ["US", "CA"] }

