[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "http://prayers-reservation-server-production.up.railway.app/:splat"
  status = 200
  force = true
